plugins {
    id("com.falsepattern.fpgradle-mc") version "3.3.0"
//    kotlin("jvm") version "2.2.0"  //If you want Kotlin. You need to also uncomment the scala line in gradle.properties, and enable Forgelin in the minecraft_fp block!
//    scala  //If you want Scala, not compatible with jabel/modern java!
    kotlin("jvm")
}

group = "xyz.uniblood"

minecraft_fp {
    // optional
    // If you want to use modern java
    java {
        compatibility = legacy //Convention
        version = JavaVersion.VERSION_17 //Convention, determined by compatibility
    }

    // REQUIRED
    // Basic information about the mod
    mod {
        modid = "arcanumunveiled"   //REQUIRED
        name = "Arcanum Unveiled"  //REQUIRED
//        version = "autogenerated from git" //Convention
        rootPkg = "$group.arcanumunveiled" //REQUIRED
    }

    // optional
    // for runClient/runServer
//    run {
//        username = "Developer" //Convention, client only
//        userUUID = "00000000-0000-4000-0000-000000000000" //optional, client only
//    }

    // optional
    // For generating an -api jar
//    api {
//        classes           = listOf() //Convention
//        packages          = listOf() //Convention
//        packagesNoRecurse = listOf() //Convention
//        ignoreRootPkg     = false    //Convention
//        includeSources    = false     //Convention
//    }

    mixin {
        pkg = "mixins"
//        pluginClass   = "MixinPlugin" //optional, requires pkg set
        extraConfigs = listOf()      //Convention
        debug = false         //Convention
        hasMixinDeps = true         //Convention
        ignoreRootPkg = false         //Convention
    }

    // optional
//    kotlin {
//        forgelinVersion = "2.2.21.0"
//        hasKotlinDeps = false  //Convention
//    }


    // optional
//    core {
//        coreModClass                   = "Core"      //optional
//        coreModIgnoreRootPkg           = false       //optional
//        accessTransformerFile          = "le_at.cfg" //optional
//        containsMixinsAndOrCoreModOnly = false       //Convention
//    }

    // optional
    // Extra settings for shadowed dependencies
//    shadow {
//        minimize = false //Convention
//        relocate = false //Convention
//    }

    // optional
    // Generates string constants you can use in code
    tokens {
        tokenClass = "Tags"
//        tokenClassIgnoreRootPkg = false         //Convention
//        modid                   = "MOD_ID"      //Convention
//        name                    = "MOD_NAME"    //Convention
//        version                 = "MOD_VERSION" //Convention
//        rootPkg                 = "ROOT_PKG"    //Convention
    }

    // optional
    // Changes the log level of the console output
//    logging {
//        level = INFO //Convention
//    }

    // optional
    // Use this if you want to publish on maven/curse/modrinth
//    publish {
//        // optional
//        // Enabled by default, makes your mod jars more reproducible between rebuilds if the source code didn't change
//        reproducibleJars = true //Convention
//        // optional
//        // If not set, tries to read CHANGELOG.md (or the file specified in the CHANGELOG_FILE env var, if set)
//        changelog = "https://github.com/myname/mymod/releases/tag/{version}"
//
//        // optional
//        maven {
//            repoUrl  = "https://example.com/"
//            repoName = "example"
//            sources  = true                    //Convention
//            group    = "${project.group}"      //Convention
//            artifact = "${mod.modid}-mc1.7.10" //Convention
//            version  = "${mod.version}"        //Convention
//            userEnv  = "MAVEN_DEPLOY_USER"     //Convention
//            passEnv  = "MAVEN_DEPLOY_PASSWORD" //Convention
//        }
//
//        // optional
//        curseforge {
//            projectId = "123456"
//            tokenEnv = "CURSEFORGE_TOKEN" //Convention
//
//            // optional
//            dependencies {
//                required("foo")
//                required("bar")
//                incompatible("baz")
//            }
//        }
//
//        // optional
//        modrinth {
//            projectId = "blah123"
//            tokenEnv = "MODRINTH_TOKEN" //Convention
//
//            // optional
//            dependencies {
//                required("bar")
//                incompatible("qux")
//            }
//        }
//    }

    //optional
    //For configuring the fpgradle update checker
    updates {
        check = true // Convention
    }
}


//val myJarInJar = jarInJar_fp("jarjar") {
//    artifactName = "examplemod-jarinjar"
//    javaCompiler = javaToolchains.compilerFor {
//        languageVersion = JavaLanguageVersion.of(21)
//        vendor = minecraft_fp.java.vendor
//    }
//}

repositories {
    //Add repositories here
    //You can use maven("reponame", "https://example.com/") as a shortcut for maven repositories.

    /*
     * Built-in maven repository convenience shortcuts:
     *
     * cursemavenEX() -> adds cursemaven, and forces all curse.maven packages to route to only it
     * modrinthEX() -> same thing but with modrinth maven
     * mavenpattern() -> FalsePattern's maven
     * jitpack() -> jitpack
     * mega() -> The MEGA team's public maven
     *
     * The exclusive(...) method can be used as a simplified wrapper on top of exclusiveContent. See the FPGradle sources for details.
     */


    exclusive(jitpack(), "com.github.MellowArpeggiation")

    mavenpattern()
    mega()
    cursemavenEX()
    horizon()
}

dependencies {

    api(deobfCurse("baubles-expanded-gtnh-1238321:7126889"))
    api(deobfCurse("thaumcraft-223628:2227552"))
    api(deobfCurse("nbtstructurelib-1388190:7259744"))
    api("com.github.MellowArpeggiation:NBTStructureLib:0.6.1:dev")

    apiSplit("com.falsepattern:falsepatternlib-mc1.7.10:1.10.5")

    annotationProcessor("com.github.bsideup.jabel:jabel-javac-plugin:1.0.0")
    compileOnly("com.github.bsideup.jabel:jabel-javac-plugin:1.0.0")
    compileOnlyApi("it.unimi.dsi:fastutil:8.5.18")

    runtimeOnlyNonPublishable(deobfCurse("et-futurum-requiem-441392:5873837"))

    runtimeOnlyNonPublishable("codechicken:notenoughitems-mc1.7.10:2.8.35-mega:dev")
    runtimeOnlyNonPublishable(deobfCurse("worldedit-225608:2309699"))
}